apiVersion: v1
kind: Service
metadata:
  name: verification-service
  namespace: kube-credential
spec:
  selector:
    app: verification
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP
